### ISSUE TITLE
music module doesn’t work as documented

### ISSUE THREAD

**Issue by kstrauser** [ColdGrub1384/Pyto#150]
I’m trying a very simple script on Pyto 11.6.1 (on iPadOS 13.4):

```python
import music

m = music.now_playing_item()

print(m)
print(m.title)
```

This fails with:

```
Traceback (most recent call last):
  File "iCloud/np2.py", line 6, in <module>
    print(m.title)
  File "Pyto.app/Lib/music.py", line 594, in title
    val = self.__item__.title
  File "Pyto.app/site-packages/rubicon/objc/api.py", line 590, in __getattr__
    raise AttributeError('%s.%s %s has no attribute %s' % (
AttributeError: rubicon.objc.api.ObjCInstance _MPMusicPlayerMediaItemProxy has no attribute title
```

...although that attribute [is documented to exist](https://pyto.readthedocs.io/en/latest/music.html#music.MediaItem.title). And although I’m not trying to use this method, the sample script:

```python
import music
music.set_queue_with_items(music.pick_music())
music.play()
```

fails when I try to run it because `pick_music` doesn’t have an “OK” or “Continue” button, so there’s no way to exit it without pressing “Cancel”, which fails with the traceback:

```
Traceback (most recent call last):
  File "iCloud/np2.py", line 2, in <module>
    music.set_queue_with_items(music.pick_music())
  File "Pyto.app/Lib/music.py", line 744, in set_queue_with_items
    collection = MPMediaItemCollection.collectionWithItems(objc_items)
  File "Pyto.app/site-packages/rubicon/objc/api.py", line 206, in __call__
    return self.method(self.receiver, *args, **kwargs)
  File "Pyto.app/site-packages/rubicon/objc/api.py", line 185, in __call__
    return meth(receiver, *args)
  File "Pyto.app/site-packages/rubicon/objc/api.py", line 123, in __call__
    arg = ns_from_py(arg)
  File "Pyto.app/site-packages/rubicon/objc/api.py", line 1106, in ns_from_py
    array.addObject(v)
  File "Pyto.app/site-packages/rubicon/objc/api.py", line 206, in __call__
    return self.method(self.receiver, *args, **kwargs)
  File "Pyto.app/site-packages/rubicon/objc/api.py", line 185, in __call__
    return meth(receiver, *args)
  File "Pyto.app/site-packages/rubicon/objc/api.py", line 123, in __call__
    arg = ns_from_py(arg)
  File "Pyto.app/site-packages/rubicon/objc/api.py", line 1115, in ns_from_py
    raise TypeError(
TypeError: Don't know how to convert a rubicon.objc.runtime.LP_objc_id to a Foundation object
```

Is there something I need to update inside Pyto, maybe?

**Comment by ColdGrub1384** [comment]
Sorry, it worked fine before iOS 13.4. I'll fix that. Thank you.

**Comment by kstrauser** [comment]
Hmm, I’m still seeing the problem after upgrading to Pyto 11.7:

![Failed now_playing_item.title screenshot](https://user-images.githubusercontent.com/295674/77974685-ba137480-72ac-11ea-8bee-40d520c15c1c.jpeg)

I rebooted my iPad, then deleted and re-installed Pyto to try to eliminate some chances for weird system issues to sneak in.

**Comment by ColdGrub1384** [comment]
Oh I'm sorry, I just fixed the second error 😓

**Comment by kstrauser** [comment]
I'm so sorry, and I promise I'm not trying to be a pest, but I'm still getting the same error (on both iPhone and iPad) with Pyto 11.7.1 on iPadOS / iOS 13.4.

**Comment by kstrauser** [comment]
I take that back - it now works currently on iPad (a thousand thanks!), but still gets the error on iPhone.

**Comment by ColdGrub1384** [comment]
That's strange, it works for me on both iPad and iPhone.

**Comment by ColdGrub1384** [comment]
Are you sure you have Pyto 11.7.1?

**Comment by kstrauser** [comment]
I'm sure. Just now, I deleted Pyto off my phone, rebooted my phone, and reinstalled Pyto (again, to make sure we're starting with a blank slate).

This is how Pyto reported its own version number:

![IMG_0768](https://user-images.githubusercontent.com/295674/78289544-34bfd800-74d7-11ea-98d7-1c01002cd519.PNG)

I hate screenshots of code, but I wanted to show that I'm running exactly the code I described above:

![IMG_0769](https://user-images.githubusercontent.com/295674/78289588-40ab9a00-74d7-11ea-9eea-3fd0224afe6b.PNG)

Same with screenshots of tracebacks. 😀 But again, just trying to show that it's the same traceback as before.

![IMG_0770](https://user-images.githubusercontent.com/295674/78289690-6a64c100-74d7-11ea-8b8c-b8089b4065ff.PNG)

It _is_ working just fine on my iPad now, though.

**Comment by kstrauser** [comment]
...and now it's failing again on my iPad.

I swear to you it was actually working yesterday when I tested it. I ran it and it worked and I was so happy to have at least one device working, but now it's failing identically to on my iPhone.

**Comment by kstrauser** [comment]
To follow up: I was very surprised and happy when it worked last night on my iPad.

This morning, it’s back to not working. I literally did nothing but plug it in to my charger overnight, and now it’s just sadness.

I mention this because it seems like perhaps it’s an OS error instead of a problem with Pyto. Pythonista has similar wrappers around MPMusicPlayer and they’re failing with the same kinds of errors. I wanted to post this so that someone else seeing these problems would have something to Google for. Even if it doesn’t fix their problem, at least they know they’re not alone.

(As someone who writes software with lots of unit and integration tests for a living, these random errors caused by outside services are _the most_ annoying things in the world to troubleshoot, aren’t they? Thanks for helping @ColdGrub1384, but I’m guessing this might not be something solvable at the app level.)
